version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: localhost
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - dev.env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
      - rabbitmq
  auditor:
    build: .
    command: python auditor.py
    links:
      - rabbitmq
  saver:
    build: .
    command: python ./audit_saver/__init__.py
    links:
      - rabbitmq
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=audit

volumes:
  postgres_data: